spring.application.name=apigateway

server.port=9090
spring.cloud.gateway.routes[0].id=servicio-nutricionista
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/nutricionistas/**

spring.cloud.gateway.routes[1].id=servicio-paciente
spring.cloud.gateway.routes[1].uri=http://localhost:8085
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/pacientes/**

spring.cloud.gateway.routes[2].id=servicio-recetas
spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/recetas/**

spring.cloud.gateway.routes[3].id=servicio-alimentos
spring.cloud.gateway.routes[3].uri=http://localhost:8083
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/alimentos/**

spring.cloud.gateway.routes[4].id=servicio-citas
spring.cloud.gateway.routes[4].uri=http://localhost:8084
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/citas/**

# ESPACIOS PARA PRÓXIMAS ACTUALIZACIONES (5 MICROSERVICIOS MÁS)
# spring.cloud.gateway.routes[5].id=servicio-6
# spring.cloud.gateway.routes[5].uri=http://localhost:8086
# spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/servicio6/**

# spring.cloud.gateway.routes[6].id=servicio-7
# spring.cloud.gateway.routes[6].uri=http://localhost:8087
# spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/servicio7/**

# spring.cloud.gateway.routes[7].id=servicio-8
# spring.cloud.gateway.routes[7].uri=http://localhost:8088
# spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/servicio8/**

# spring.cloud.gateway.routes[8].id=servicio-9
# spring.cloud.gateway.routes[8].uri=http://localhost:8089
# spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/servicio9/**

# spring.cloud.gateway.routes[9].id=servicio-10
# spring.cloud.gateway.routes[9].uri=http://localhost:8091
# spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/servicio10/**

# CONFIGURACIÓN GLOBAL DE CORS (Evita el Failed to Fetch)
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:9090
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

# CONFIGURACIÓN DE EUREKA
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# 5. CONFIGURACIÓN DEL MENÚ DESPLEGABLE DE SWAGGER UI

springdoc.swagger-ui.urls[0].name=Servicio Nutricionistas
springdoc.swagger-ui.urls[0].url=/api/v1/nutricionistas/v3/api-docs

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[1].name=Servicio Pacientes
springdoc.swagger-ui.urls[1].url=/api/v1/pacientes/v3/api-docs

#springdoc.swagger-ui.urls[2].name=Servicio Recetas
#springdoc.swagger-ui.urls[2].url=/api/v1/recetas/v3/api-docs

#springdoc.swagger-ui.urls[3].name=Servicio Alimentos
#springdoc.swagger-ui.urls[3].url=/api/v1/alimentos/v3/api-docs

#springdoc.swagger-ui.urls[4].name=Servicio Citas
#springdoc.swagger-ui.urls[4].url=/api/v1/citas/v3/api-docs

# ESPACIOS PARA PRÓXIMAS ACTUALIZACIONES
# springdoc.swagger-ui.urls[5].name=Servicio 6
# springdoc.swagger-ui.urls[5].url=/api/v1/servicio6/v3/api-docs

# springdoc.swagger-ui.urls[6].name=Servicio 7
# springdoc.swagger-ui.urls[6].url=/api/v1/servicio7/v3/api-docs

# springdoc.swagger-ui.urls[7].name=Servicio 8
# springdoc.swagger-ui.urls[7].url=/api/v1/servicio8/v3/api-docs

# springdoc.swagger-ui.urls[8].name=Servicio 9
# springdoc.swagger-ui.urls[8].url=/api/v1/servicio9/v3/api-docs

# springdoc.swagger-ui.urls[9].name=Servicio 10
# springdoc.swagger-ui.urls[9].url=/api/v1/servicio10/v3/api-docs